@startuml

skinparam DefaultTextAlignment center

rectangle "IAR Project" as IarProject
rectangle "IAR Workbench" as IarWorkbench
rectangle "IAR Toolchains" as IarToolchain
rectangle "IAR Compilers" as IarCompiler
rectangle "Configurations" as Configurations
rectangle "Defines" as Defines
rectangle "Include Paths" as IncludePaths
rectangle "Pre Include Files" as PreIncludeFiles
rectangle "Compiler Intrinsics" as Intrinsics
rectangle "Target File\nc_cpp_properties.json" as TargetFile

IarWorkbench -- IarToolchain
IarToolchain -- IarCompiler

IarProject -- Configurations

IarCompiler --> Defines
IarCompiler --> IncludePaths
IarCompiler -> Intrinsics

Configurations --> Defines
Configurations --> IncludePaths
Configurations --> PreIncludeFiles

Intrinsics --> Defines

Defines --> TargetFile
IncludePaths --> TargetFile
PreIncludeFiles --> TargetFile

rectangle "Microsoft\nvscode-cpptools" as MicrosoftCppTools

TargetFile <-- MicrosoftCppTools: uses

@enduml
