/// <reference path="HeartbeatService.d.ts" />
//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import shared_ttypes = require('./shared_types');


import ttypes = require('./cspy_types');
import DkNotifyConstant = ttypes.DkNotifyConstant
import DkCoreStatusConstants = ttypes.DkCoreStatusConstants
import DkLoggingCategoryConstant = ttypes.DkLoggingCategoryConstant
import BasicExprType = ttypes.BasicExprType
import DEBUGGER_SERVICE = ttypes.DEBUGGER_SERVICE
import DEBUGEVENT_SERVICE = ttypes.DEBUGEVENT_SERVICE
import CONTEXT_MANAGER_SERVICE = ttypes.CONTEXT_MANAGER_SERVICE
import MEMORY_SERVICE = ttypes.MEMORY_SERVICE
import SessionConfiguration = ttypes.SessionConfiguration
import DebugEvent = ttypes.DebugEvent
import InspectionContextChangedEvent = ttypes.InspectionContextChangedEvent
import BaseContextChangedEvent = ttypes.BaseContextChangedEvent
import LogEvent = ttypes.LogEvent
import Thread = ttypes.Thread
import ExprValue = ttypes.ExprValue
import ModuleData = ttypes.ModuleData
import NamedLocationMask = ttypes.NamedLocationMask
import NamedLocation = ttypes.NamedLocation
import ExtraDebugFile = ttypes.ExtraDebugFile
import ModuleLoadingOptions = ttypes.ModuleLoadingOptions
import ResetStyles = ttypes.ResetStyles
import DebugSettings = ttypes.DebugSettings
import HeartbeatService = require('./HeartbeatService');

/**
 * Main C-SPY service.
 */
declare class Client extends HeartbeatService.Client {
  #output: thrift.TTransport;
  #pClass: thrift.TProtocol;
  #_seqid: number;

  constructor(output: thrift.TTransport, pClass: { new(trans: thrift.TTransport): thrift.TProtocol });

  getVersionString(): Q.Promise<string>;

  getVersionString(callback?: (error: void, response: string)=>void): void;

  startSession(sessionConfig: SessionConfiguration): Q.Promise<void>;

  startSession(sessionConfig: SessionConfiguration, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  stopSession(): Q.Promise<void>;

  stopSession(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getDebugSettings(): Q.Promise<DebugSettings>;

  getDebugSettings(callback?: (error: shared_ttypes.CSpyException, response: DebugSettings)=>void): void;

  setDebugSettings(settings: DebugSettings): Q.Promise<void>;

  setDebugSettings(settings: DebugSettings, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  exit(): Q.Promise<void>;

  exit(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  isOnline(): Q.Promise<boolean>;

  isOnline(callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  loadModule(filename: string): Q.Promise<void>;

  loadModule(filename: string, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  loadModuleWithOptions(filename: string, options: ModuleLoadingOptions): Q.Promise<void>;

  loadModuleWithOptions(filename: string, options: ModuleLoadingOptions, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  flashModule(boardFile: string, executable: string, arguments: string[], extraExecutables: string[]): Q.Promise<void>;

  flashModule(boardFile: string, executable: string, arguments: string[], extraExecutables: string[], callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getFlashPasses(boardFile: string): Q.Promise<string[][]>;

  getFlashPasses(boardFile: string, callback?: (error: shared_ttypes.CSpyException, response: string[][])=>void): void;

  eraseFlash(boardFile: string, nPasses: boolean[]): Q.Promise<void>;

  eraseFlash(boardFile: string, nPasses: boolean[], callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getModules(): Q.Promise<ModuleData[]>;

  getModules(callback?: (error: shared_ttypes.CSpyException, response: ModuleData[])=>void): void;

  loadMacroFile(macro: string): Q.Promise<void>;

  loadMacroFile(macro: string, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  unloadMacroFile(macro: string): Q.Promise<void>;

  unloadMacroFile(macro: string, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  runToULE(ule: string, allowSingleStep: boolean): Q.Promise<void>;

  runToULE(ule: string, allowSingleStep: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getMulticoreFlags(): Q.Promise<Int64>;

  getMulticoreFlags(callback?: (error: shared_ttypes.CSpyException, response: Int64)=>void): void;

  getThreadList(): Q.Promise<Thread[]>;

  getThreadList(callback?: (error: shared_ttypes.CSpyException, response: Thread[])=>void): void;

  isActiveThread(t: Thread): Q.Promise<boolean>;

  isActiveThread(t: Thread, callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  evalExpression(ref: shared_ttypes.ContextRef, expr: string, subExprIndex: number[], format: shared_ttypes.ExprFormat, prefix: boolean): Q.Promise<ExprValue>;

  evalExpression(ref: shared_ttypes.ContextRef, expr: string, subExprIndex: number[], format: shared_ttypes.ExprFormat, prefix: boolean, callback?: (error: shared_ttypes.CSpyException, response: ExprValue)=>void): void;

  assignExpression(ref: shared_ttypes.ContextRef, expr: string, subExprIndex: number[], rvalue: ExprValue): Q.Promise<void>;

  assignExpression(ref: shared_ttypes.ContextRef, expr: string, subExprIndex: number[], rvalue: ExprValue, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getSubExpressionLabels(ref: shared_ttypes.ContextRef, rootExpr: string, subExprIndex: number[], startIndex: number, length: number, treatPointerAsArray: boolean): Q.Promise<string[]>;

  getSubExpressionLabels(ref: shared_ttypes.ContextRef, rootExpr: string, subExprIndex: number[], startIndex: number, length: number, treatPointerAsArray: boolean, callback?: (error: shared_ttypes.CSpyException, response: string[])=>void): void;

  getLocationNames(): Q.Promise<string[]>;

  getLocationNames(callback?: (error: shared_ttypes.CSpyException, response: string[])=>void): void;

  getLocationNamesInGroup(group: string): Q.Promise<string[]>;

  getLocationNamesInGroup(group: string, callback?: (error: shared_ttypes.CSpyException, response: string[])=>void): void;

  getRegisterGroups(): Q.Promise<string[]>;

  getRegisterGroups(callback?: (error: shared_ttypes.CSpyException, response: string[])=>void): void;

  getNamedLocation(name: string): Q.Promise<NamedLocation>;

  getNamedLocation(name: string, callback?: (error: shared_ttypes.CSpyException, response: NamedLocation)=>void): void;

  getCoreState(core: number): Q.Promise<DkCoreStatusConstants>;

  getCoreState(core: number, callback?: (error: shared_ttypes.CSpyException, response: DkCoreStatusConstants)=>void): void;

  getNumberOfCores(): Q.Promise<number>;

  getNumberOfCores(callback?: (error: shared_ttypes.CSpyException, response: number)=>void): void;

  getCoreDescription(core: number): Q.Promise<string>;

  getCoreDescription(core: number, callback?: (error: void, response: string)=>void): void;

  getCycleCounter(core: number): Q.Promise<Int64>;

  getCycleCounter(core: number, callback?: (error: shared_ttypes.CSpyException, response: Int64)=>void): void;

  getCyclesPerSecond(): Q.Promise<Int64>;

  getCyclesPerSecond(callback?: (error: shared_ttypes.CSpyException, response: Int64)=>void): void;

  hasCoreStoppedDeliberately(core: number): Q.Promise<boolean>;

  hasCoreStoppedDeliberately(core: number, callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  setResetStyles(id: number): Q.Promise<void>;

  setResetStyles(id: number, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getResetStyles(): Q.Promise<ResetStyles[]>;

  getResetStyles(callback?: (error: shared_ttypes.CSpyException, response: ResetStyles[])=>void): void;

  reset(): Q.Promise<void>;

  reset(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  go(): Q.Promise<void>;

  go(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  goCore(core: number): Q.Promise<void>;

  goCore(core: number, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  stop(): Q.Promise<void>;

  stop(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  stopCore(core: number): Q.Promise<void>;

  stopCore(core: number, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  multiGo(core: number): Q.Promise<void>;

  multiGo(core: number, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  step(enterFunctionsWithoutSource: boolean): Q.Promise<void>;

  step(enterFunctionsWithoutSource: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  stepOver(enterFunctionsWithoutSource: boolean): Q.Promise<void>;

  stepOver(enterFunctionsWithoutSource: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  nextStatement(enterFunctionsWithoutSource: boolean): Q.Promise<void>;

  nextStatement(enterFunctionsWithoutSource: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  stepOut(): Q.Promise<void>;

  stepOut(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  instructionStep(): Q.Promise<void>;

  instructionStep(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  instructionStepOver(): Q.Promise<void>;

  instructionStepOver(callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  goToLocation(location: shared_ttypes.Location): Q.Promise<void>;

  goToLocation(location: shared_ttypes.Location, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  goToLocations(locations: shared_ttypes.Location[]): Q.Promise<void>;

  goToLocations(locations: shared_ttypes.Location[], callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  supportsExceptions(): Q.Promise<boolean>;

  supportsExceptions(callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  getBreakOnThrow(): Q.Promise<boolean>;

  getBreakOnThrow(callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  setBreakOnThrow(enable: boolean): Q.Promise<void>;

  setBreakOnThrow(enable: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getBreakOnUncaughtException(): Q.Promise<boolean>;

  getBreakOnUncaughtException(callback?: (error: shared_ttypes.CSpyException, response: boolean)=>void): void;

  setBreakOnUncaughtException(enable: boolean): Q.Promise<void>;

  setBreakOnUncaughtException(enable: boolean, callback?: (error: shared_ttypes.CSpyException, response: void)=>void): void;

  getZoneByName(name: string): Q.Promise<shared_ttypes.ZoneInfo>;

  getZoneByName(name: string, callback?: (error: shared_ttypes.CSpyException, response: shared_ttypes.ZoneInfo)=>void): void;

  getZoneById(id: number): Q.Promise<shared_ttypes.ZoneInfo>;

  getZoneById(id: number, callback?: (error: shared_ttypes.CSpyException, response: shared_ttypes.ZoneInfo)=>void): void;

  getAllZones(): Q.Promise<shared_ttypes.ZoneInfo[]>;

  getAllZones(callback?: (error: shared_ttypes.CSpyException, response: shared_ttypes.ZoneInfo[])=>void): void;

  getTraceTime(): Q.Promise<Int64>;

  getTraceTime(callback?: (error: void, response: Int64)=>void): void;
}

declare class Processor extends HeartbeatService.Processor {
  #_handler: object;

  constructor(handler: object);
  process(input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getVersionString(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_startSession(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_stopSession(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getDebugSettings(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_setDebugSettings(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_exit(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_isOnline(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_loadModule(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_loadModuleWithOptions(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_flashModule(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getFlashPasses(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_eraseFlash(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getModules(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_loadMacroFile(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_unloadMacroFile(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_runToULE(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getMulticoreFlags(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getThreadList(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_isActiveThread(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_evalExpression(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_assignExpression(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getSubExpressionLabels(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getLocationNames(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getLocationNamesInGroup(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getRegisterGroups(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getNamedLocation(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getCoreState(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getNumberOfCores(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getCoreDescription(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getCycleCounter(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getCyclesPerSecond(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_hasCoreStoppedDeliberately(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_setResetStyles(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getResetStyles(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_reset(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_go(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_goCore(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_stop(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_stopCore(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_multiGo(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_step(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_stepOver(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_nextStatement(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_stepOut(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_instructionStep(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_instructionStepOver(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_goToLocation(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_goToLocations(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_supportsExceptions(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getBreakOnThrow(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_setBreakOnThrow(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getBreakOnUncaughtException(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_setBreakOnUncaughtException(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getZoneByName(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getZoneById(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getAllZones(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
  process_getTraceTime(seqid: number, input: thrift.TProtocol, output: thrift.TProtocol): void;
}
