//
// Autogenerated by Thrift Compiler (0.14.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import ServiceRegistry_ttypes = require('./ServiceRegistry_types');



declare class ServiceConfig {
  public name: string;
  public libraryName: string;
  public spawnNewProcess: boolean;
  public startupEntryPoint: string;
  public shutdownEntryPoint: string;
  public registerInLauncher: boolean;

    constructor(args?: { name: string; libraryName: string; spawnNewProcess: boolean; startupEntryPoint: string; shutdownEntryPoint: string; registerInLauncher: boolean; });
  read(input: Object): void;
  write(input: Object): void;
}

declare class LauncherConfig {
  public useInternalRegistry: boolean;
  public externalRegistryLocation: ServiceRegistry_ttypes.ServiceLocation;
  public preferredTransports: ServiceRegistry_ttypes.Transport[];

    constructor(args?: { useInternalRegistry: boolean; externalRegistryLocation: ServiceRegistry_ttypes.ServiceLocation; preferredTransports: ServiceRegistry_ttypes.Transport[]; });
  read(input: Object): void;
  write(input: Object): void;
}

declare var SERVICE_MANAGER_SERVICE: string;
